Mortality
jbathmann/pyMANGA pull request #108
Opened 2021-08-25 09:28 UTC by mcwimm

This is a selection of Mortality concepts applicable to SimpleBettina and NetworkBettina (see docs).

This should not affect the functionality of previous scripts. If no mortality-concept is chosen, trees die immediatly if grow < 0 (as currently in the master).

2021-08-30 11:53 UTC, jbathmann commented on TreeOutputLib/OneFile/OneFile.py
> +#!/usr/bin/env python3
unrelated. please remove from this pr

2021-08-30 11:53 UTC, jbathmann commented on TreeOutputLib/OneTimestepOneFile/OneTimestepOneFile.py
>              " and geometric" + " measures ", self.geometry_outputs,
unrelated. please remove from this pr

2021-08-30 12:05 UTC, jbathmann reviewed
I like, where this is going!

2021-08-30 12:05 UTC, jbathmann commented on TreeModelLib/GrowthAndDeathDynamics/NetworkBettina/NetworkBettina.py
> +            print(
see previous comment

2021-08-30 12:05 UTC, jbathmann commented on TreeModelLib/GrowthAndDeathDynamics/SimpleBettina/SimpleBettina.py
> +        return growth_concept_information
can you do this in a "cleaner" way? Maybe by adding it to the normal GrowthConcept-class?

2021-08-30 12:05 UTC, jbathmann commented on TreeModelLib/GrowthAndDeathDynamics/Mortality/modules/MinGirthGrowth.py
> +                      "threshold.")
This is repeated from other classes... inheritance?

2021-08-30 12:05 UTC, jbathmann commented on TreeModelLib/GrowthAndDeathDynamics/Mortality/modules/Memory.py
> +        period_in_sec = self.period * 3600 * 24 * 365
what are you ding here? the input should be in SI units, as we are using SI throughout the model

2021-08-30 12:05 UTC, jbathmann commented on TreeModelLib/GrowthAndDeathDynamics/Mortality/modules/MinGirthGrowth.py
> +              str(self.period) + " years.")
please inherit repeated content

2021-08-30 12:05 UTC, jbathmann commented on TreeModelLib/GrowthAndDeathDynamics/Mortality/modules/Random.py
> +        steps_per_year = (3600 * 24 * 365) / args.time
??
A year has 365.25 days. ;-)

2021-08-30 15:42 UTC, mcwimm commented on TreeOutputLib/OneFile/OneFile.py
> +#!/usr/bin/env python3
solved

2021-08-30 15:42 UTC, mcwimm commented on TreeOutputLib/OneTimestepOneFile/OneTimestepOneFile.py
>              " and geometric" + " measures ", self.geometry_outputs,
solved

2021-08-30 15:42 UTC, mcwimm commented on TreeOutputLib/OneTimestepOneFilePerGroup/OneTimestepOneFilePerGroup.py
>                  string = ""
solved

2021-08-30 15:43 UTC, mcwimm commented on TreeOutputLib/__init__.py
>  from .TreeOutput import TreeOutput
solved

2021-08-30 15:46 UTC, mcwimm commented on Documentation/ProjectFile/MangaProject/tree_dynamics/tree_growth_and_death/Mortality/c_Mortality.md
> +
This fits to the current implementation as the description of concepts here is just a explanation for possible inputs for the tag `mortality`. Nonetheless, this might change if we restructure the mortality stuff...

2021-08-30 15:47 UTC, mcwimm commented on TreeModelLib/GrowthAndDeathDynamics/Mortality/modules/MinGirthGrowth.py
> +                      "threshold.")
I think it's not repeated as each mortality class contains another approach to calculate the survival factor in `getSurvival`.

2021-08-30 15:56 UTC, mcwimm commented on TreeModelLib/GrowthAndDeathDynamics/Mortality/modules/MinGirthGrowth.py
> +              str(self.period) + " years.")
parameters differ between concepts

2021-08-30 15:56 UTC, mcwimm commented on TreeModelLib/GrowthAndDeathDynamics/Mortality/modules/Random.py
> +        steps_per_year = (3600 * 24 * 365) / args.time
right :) changed

2021-08-30 15:56 UTC, mcwimm commented on TreeOutputLib/OneTreeOneFile/OneTreeOneFile.py
>  #  A line containing time, position, desired geometric measures and desired
solved

2021-08-30 15:56 UTC, mcwimm commented on TreeOutputLib/TreeOutput.py
>              self.iniOneTimestepOneFile(args)
solved

2021-08-30 15:58 UTC, mcwimm commented on Documentation/ProjectFile/MangaProject/tree_dynamics/tree_growth_and_death/Mortality/c_Mortality.md
> +Use `<period> 2 </period>` and `<threshold> 0.5 </threshold>` to modify concept parameters.
I would prefer default inputs as there's not much information available on these parameters. I presume that we'll usually use the default values.

2021-08-30 16:04 UTC, mcwimm commented on Documentation/project_dox/MangaProject/tree_dynamics/tree_growth_and_death/t_type.dox
> +- Mortality
At the moment, mortality parameters are additional/ optional parameters for growth-and-death-concepts and they are defined as follows:

```
<tree_growth_and_death>  
     <type> SimpleBettina</type>  
     <mortality> Memory </mortality>  
     <period> 1e9  </period>  
     <threshold> 0.5 </threshold>
</tree_growth_and_death>
```

2021-08-30 16:04 UTC, mcwimm commented on TreeModelLib/GrowthAndDeathDynamics/NetworkBettina/NetworkBettina.py
> +                        "mortality", "threshold", "period"]
No, it's an optional input. If it is not defined the mortality concept 'NoGrowth' is used (this is the current mortality concept in the master).

2021-08-30 16:05 UTC, mcwimm commented on TreeModelLib/GrowthAndDeathDynamics/Mortality/modules/Memory.py
> +        period_in_sec = self.period * 3600 * 24 * 365
changed :)

2021-08-31 06:53 UTC, jbathmann commented on Documentation/ProjectFile/MangaProject/tree_dynamics/tree_growth_and_death/Mortality/c_Mortality.md
> +
ok. how do you proceed wth this?

2021-08-31 06:53 UTC, jbathmann commented on Documentation/ProjectFile/MangaProject/tree_dynamics/tree_growth_and_death/Mortality/c_Mortality.md
> +Use `<period> 2 </period>` and `<threshold> 0.5 </threshold>` to modify concept parameters.
ok...

2021-08-31 06:55 UTC, jbathmann commented on Documentation/project_dox/MangaProject/tree_dynamics/tree_growth_and_death/t_type.dox
> +- Mortality
<tree_growth_and_death>  
     <type> SimpleBettina</type>  
     <mortality>
        <type> Memory </type> 
        <period> 1e9  </period>  
         <threshold> 0.5 </threshold>
     </mortality>  
</tree_growth_and_death>

2021-08-31 06:57 UTC, jbathmann commented on Documentation/project_dox/MangaProject/tree_dynamics/tree_growth_and_death/t_type.dox
> +- Mortality
is it possible to follow this structure? (no idea how to format correctly here... -.-)

2021-08-31 06:58 UTC, jbathmann commented on TreeModelLib/GrowthAndDeathDynamics/NetworkBettina/NetworkBettina.py
> +                        "mortality", "threshold", "period"]
but missing_tags is listing the required inputs (see line 165)

2021-08-31 06:58 UTC, jbathmann commented on TreeModelLib/GrowthAndDeathDynamics/Mortality/modules/MinGirthGrowth.py
> +                      "threshold.")
and there is also no partwise repeating?

2021-09-02 10:40 UTC, mcwimm commented on TreeModelLib/GrowthAndDeathDynamics/Mortality/modules/MinGirthGrowth.py
> +                      "threshold.")
Not any more because there is a new concept (after discussion with @zaphod-bx ) and others (Memory, MinGirthGrowth) were removed.

2021-09-02 10:40 UTC, mcwimm commented on TreeModelLib/GrowthAndDeathDynamics/SimpleBettina/SimpleBettina.py
> +        return growth_concept_information
Solved

2021-09-02 10:40 UTC, mcwimm commented on Documentation/ProjectFile/MangaProject/tree_dynamics/tree_growth_and_death/Mortality/c_Mortality.md
> +
Solved

2021-09-02 11:02 UTC, mcwimm commented
@jbathmann I changed three major thinks with the last commits:

- I deleted the former concepts ('Memory' and 'MinGirthGrowth') after a discussion with @zaphod-bx about their usefullness.
- The mortality concept 'NoGrowth' is now the super class for all other mortality concepts, containing all required methods.
- I restructured the Mortality directory in order to align the structure to other sections such as belowground competition. However, that is not the structure you suggested... The mortality concept is still initialized by the growth concept.

2021-09-02 12:44 UTC, jbathmann commented
For me it is ready to merge...

2021-09-03 11:59 UTC, jbathmann commented on TreeModelLib/GrowthAndDeathDynamics/NetworkBettina/NetworkBettina.py
> +
please move this to super()

2021-09-03 12:01 UTC, jbathmann requested changes
Please add the mortality stuff to the superclass (treemodel) and than just call it in the constructor of your individual concepts, if need be.

2021-09-03 12:04 UTC, jbathmann commented on TreeModelLib/GrowthAndDeathDynamics/SimpleBettina/SimpleBettina.py
>              self.survive = 0
why here?!

2021-09-03 12:51 UTC, jbathmann commented on TreeModelLib/GrowthAndDeathDynamics/SimpleBettina/SimpleBettina.py
>              self.survive = 0
nevermind

2021-09-07 06:37 UTC, mcwimm commented on TreeModelLib/GrowthAndDeathDynamics/NetworkBettina/NetworkBettina.py
> +
solved.

2021-09-10 07:48 UTC, mcwimm commented
> Please add the mortality stuff to the superclass (treemodel) and than just call it in the constructor of your individual concepts, if need be.

Done.

2021-09-13 07:15 UTC, jbathmann approved these changes

2021-09-13 07:15 UTC, jbathmann commented
looks ready to me.

2021-09-13 09:31 UTC, merged