MANGA as OGS boundary condition
jbathmann/pyMANGA pull request #110
Opened 2021-08-31 08:26 UTC by mcwimm

The below-ground concept `OGSLargeScale3D` is adapted in order to use ExternalTimeStepping.

2021-08-31 08:30 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3D/OGSLargeScale3D.py
>          parameter = tree.getParameter()
Please put the changes on existing code to seperate PR which we can merge first

2021-08-31 08:32 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/SimpleNetwork/SimpleNetwork.py
>      def getRGFforGrowthAndDeath(self, pairs):
Please put in seperate pr, as it is not related

2021-08-31 08:32 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/SimpleTest/SimpleTest.py
> +        return self.external_information
this should be removed by rebase?

2021-08-31 08:35 UTC, jbathmann requested changes
Please let me know, when you have
i) removed the already merged changes (#99)
ii) moved unrelated stuff to another pr
:)

2021-08-31 09:59 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3D/OGSLargeScale3D.py
>          parameter = tree.getParameter()
ok. see #111

2021-08-31 10:25 UTC, jbathmann requested changes

2021-08-31 10:25 UTC, jbathmann commented on test/LargeTests/Test_Setups_large/external_setup/ExternalOGS.xml
> +            <ogs_project_folder> /Users/admin/Documents/GRIN/git_repos/pyMANGA/test/LargeTests/Test_Setups_large/external_setup/ </ogs_project_folder>
I think this does not work

2021-08-31 10:25 UTC, jbathmann commented on test/LargeTests/Test_Setups_large/external_setup/ExternalOGS.xml
> +        <parameter_output> k_geom </parameter_output>
remove, if output is set to none?

2021-08-31 10:25 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/python_source.py
> +sys.path.append("/Users/admin/Documents/GRIN/git_repos/")
can replace this?

2021-08-31 10:25 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/python_source.py
> +xml_file = "ExternalOGS.xml"
loads of hardcoding

2021-08-31 10:25 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/python_source.py
> +                if t > t_before:
have you checked with reduced timestepping in adapting ogs timestepping?

2021-08-31 10:25 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/OGSLargeScale3DExternal.py
> +
What is new compared to the initial implementation?

2021-08-31 10:25 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/OGSLargeScale3DExternal.py
> +        self._tree_salinity = np.empty(self.no_trees)
I think this can be moved to "calculate..."

2021-08-31 10:25 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/OGSLargeScale3DExternal.py
> +        self.calculateTreeSalinity()
where is this?

2021-08-31 10:25 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/OGSLargeScale3DExternal.py
> +            tree_contribution = self.tree_water_uptake[tree_id]
can you move this up?

2021-08-31 10:25 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/OGSLargeScale3DExternal.py
> +        self.calculateTreeSalinity()
found it now, but it is a bit hidden...

2021-08-31 10:25 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/OGSLargeScale3DExternal.py
> +    def calculateTreeContribution(self):
does this differ from the super class? is it possible to make it the same in both classes?

2021-08-31 10:25 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/OGSLargeScale3DExternal.py
> +        R = root_surface_resistance + xylem_resistance
variables are not given with capital letters

2021-08-31 10:48 UTC, mcwimm commented on test/LargeTests/Test_Setups_large/external_setup/ExternalOGS.xml
> +            <ogs_project_folder> /Users/admin/Documents/GRIN/git_repos/pyMANGA/test/LargeTests/Test_Setups_large/external_setup/ </ogs_project_folder>
with your working directory, it should work

2021-08-31 10:49 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/python_source.py
> +                if t > t_before:
what do you mean?

2021-08-31 10:50 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/python_source.py
> +xml_file = "ExternalOGS.xml"
right. but how to avoid this? Especially, as this file and runModel are only examples that can be used to use the package in the future

2021-08-31 10:55 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/OGSLargeScale3DExternal.py
> +    def calculateTreeContribution(self):
yes, it differs. in super() bg-resources are splitted... in super(), calculateBelowgroundResources() calculates the bg-factor while in OGS...External this method calculates a rate

2021-08-31 10:59 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/OGSLargeScale3DExternal.py
> +        R = root_surface_resistance + xylem_resistance
solved

2021-08-31 11:01 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/OGSLargeScale3DExternal.py
> +            tree_contribution = self.tree_water_uptake[tree_id]
solved

2021-08-31 11:01 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/OGSLargeScale3DExternal.py
> +        self.calculateTreeSalinity()
solved

2021-08-31 11:01 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/SimpleNetwork/SimpleNetwork.py
>      def getRGFforGrowthAndDeath(self, pairs):
solved

2021-08-31 11:01 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/SimpleTest/SimpleTest.py
> +        return self.external_information
solved

2021-08-31 11:06 UTC, mcwimm commented on test/LargeTests/Test_Setups_large/external_setup/ExternalOGS.xml
> +        <parameter_output> k_geom </parameter_output>
changed

2021-08-31 11:26 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/python_source.py
> +sys.path.append("/Users/admin/Documents/GRIN/git_repos/")
how?

2021-08-31 11:29 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/OGSLargeScale3DExternal.py
> +        self._tree_salinity = np.empty(self.no_trees)
right. solved

2021-08-31 12:12 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/python_source.py
> +sys.path.append("/Users/admin/Documents/GRIN/git_repos/")
I think it is only necessary, if MANGA is not installed via pip or not added to the path variable, right? so you could just give a note here, that it is supposed to be added to the path

2021-08-31 12:13 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/python_source.py
> +xml_file = "ExternalOGS.xml"
good question

2021-08-31 12:14 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/python_source.py
> +                if t > t_before:
as far as i understood, this intends to avoid troubles if ogs reduces the timestep due to missed convergence. Did you check, whether it does the job?

2021-08-31 12:15 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/OGSLargeScale3DExternal.py
> +    def calculateTreeContribution(self):
ok. is it possible to either calculate the bg-factor or a rate such that both implementations align?

2021-08-31 12:16 UTC, jbathmann commented on test/LargeTests/Test_Setups_large/external_setup/ExternalOGS.xml
> +            <ogs_project_folder> /Users/admin/Documents/GRIN/git_repos/pyMANGA/test/LargeTests/Test_Setups_large/external_setup/ </ogs_project_folder>
right. it's confusing, though. How did @jvollhueter  solve this in the test examples?

2021-08-31 14:48 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/python_source.py
> +sys.path.append("/Users/admin/Documents/GRIN/git_repos/")
As the MANGA package is not available yet, this line is needed. However, we could insert dummy directories and a descriptions as these files serve only as an example (same for the comment below).

2021-08-31 14:50 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/python_source.py
> +                if t > t_before:
I didn't check the OGS time steps but my MANGA output files seem to be correct (i.e. increasing in time).

2021-09-01 08:31 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/python_source.py
> +sys.path.append("/Users/admin/Documents/GRIN/git_repos/")
That's a great idea!

2021-09-01 08:33 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/python_source.py
> +                if t > t_before:
fine.
what about adding something like a delta_t_min, which must be reached before bettina is progressed?
i.e. t - delta_t_min - t_before > 0

2021-09-02 10:49 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/python_source.py
> +                if t > t_before:
This is covered by the case `manga_timestep_days > 0` because this defines the minimum MANGA time step length. If this parameter is set to 5 days, for example, MANGA progresses after 5 days at the earliest (no matter how many OGS time steps happen in between) and if OGS time step length is greater than 5 days, MANGA progresses with each OGS time step.

2021-09-02 11:19 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/python_source.py
> +sys.path.append("/Users/admin/Documents/GRIN/git_repos/")
solved

2021-09-02 11:19 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/python_source.py
> +xml_file = "ExternalOGS.xml"
solved with dummy directories

2021-09-02 12:07 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/OGSLargeScale3DExternal/OGSLargeScale3DExternal.py
> +    def calculateTreeContribution(self):
yes, I tried it. Could you please check the equations!?
FYI: the next pull request (external Network concept) will contain many changes, i.e. function splitting, in the super classes...

2021-09-02 12:42 UTC, merged