New BG Network concepts
jbathmann/pyMANGA pull request #112
Opened 2021-09-02 15:26 UTC by mcwimm

This PR contains two 'new' bg network concepts which are extensions of OGS...3D and OGS...3DExternal.

2021-09-03 14:47 UTC, jbathmann requested changes
This is to much for one PR

Can you try to do first things first? otherwise i can't keep an overview/follow your thinking

2021-09-06 15:46 UTC, mcwimm commented
> This is to much for one PR
> 
> Can you try to do first things first? otherwise i can't keep an overview/follow your thinking

Yes. Please start with PR #115

2021-09-07 13:21 UTC, jbathmann commented
> > This is to much for one PR
> > Can you try to do first things first? otherwise i can't keep an overview/follow your thinking
> 
> Yes. Please start with PR #115

merged. how to proceed? :)

2021-09-07 14:31 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/NetworkOGSLargeScale3D/NetworkOGSLargeScale3D.py
> +        self._psi_osmo = []
this is so smooth! :)

2021-09-07 14:33 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/NetworkOGSLargeScale3D/NetworkOGSLargeScale3D.py
> +
puh.. why do we neet OGSLarScale3D.addTree here?

2021-09-07 14:34 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/NetworkOGSLargeScale3D/NetworkOGSLargeScale3D.py
> +        self.calculateBGresourcesTree()
this is iterating on all trees?

2021-09-07 14:35 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/NetworkOGSLargeScale3D/NetworkOGSLargeScale3D.py
> +        print("OGS-calculation done.")
why is this not used from super()?

2021-09-07 14:35 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/NetworkOGSLargeScale3D/NetworkOGSLargeScale3D.py
> +                    "'" + path.join(self._ogs_project_folder,
couldn't this be reused?

2021-09-08 09:10 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/NetworkOGSLargeScale3D/NetworkOGSLargeScale3D.py
> +        self._psi_osmo = []
Yeah :)

2021-09-08 09:21 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/NetworkOGSLargeScale3D/NetworkOGSLargeScale3D.py
> +
We don't need OGSLarScale3D.addTree here because in `OGSLargeScale3D` the water uptake (constant contribution and salinity prefector) is calculated for the individual tree (`addTree`) while in all Network concepts we need the information of all trees at first to calculate water uptake etc of the network, therefore, this is calculated in `calculateBelowgroundResources`.

However, I noticed that we can inherit more functionality from `OGSLargeScale3D`... which is now included...

2021-09-08 09:28 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/NetworkOGSLargeScale3D/NetworkOGSLargeScale3D.py
> +        self.calculateBGresourcesTree()
Yes, to run this functions we need the whole population first...

2021-09-08 09:31 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/NetworkOGSLargeScale3D/NetworkOGSLargeScale3D.py
> +                    "'" + path.join(self._ogs_project_folder,
Not completely as different files are copied... but I think the next PR (preparation for new bg concept `NetworkOGSLargeScale3DExternal` will cover modifications to allow more inheritance from super(). Should I include this changes in this PR?

2021-09-08 09:32 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/NetworkOGSLargeScale3D/NetworkOGSLargeScale3D.py
> +        print("OGS-calculation done.")
It differes from super because different files are needed. But this will be solved in the next PR (see comment below).

2021-09-08 09:33 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/NetworkOGSLargeScale3D/NetworkOGSLargeScale3D.py
> +        self.calculateBGresourcesTree()
I updated all super() functions calls to clarify who is super here.

2021-09-08 14:15 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/NetworkOGSLargeScale3D/NetworkOGSLargeScale3D.py
> +                    "'" + path.join(self._ogs_project_folder,
no, it's fine :)

2021-09-08 14:17 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/NetworkOGSLargeScale3D/NetworkOGSLargeScale3D.py
> +        SimpleNetwork.calculateBGresourcesTree()
ok. this stuff is pretty cool. do you know that it is doing exactly what you wanted before the commit?

2021-09-08 14:18 UTC, jbathmann approved these changes

2021-09-08 14:19 UTC, jbathmann commented
not tested but reviewed. If you say it works, it is ready to merge from my side. :+1:

2021-09-08 15:41 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/NetworkOGSLargeScale3D/NetworkOGSLargeScale3D.py
> +        SimpleNetwork.calculateBGresourcesTree()
Of course not :/ I fixed it, and tested it. It works now. I also uploaded a small test setup for OGSLarge... and NetworkOGS...

2021-09-08 16:31 UTC, mcwimm commented
> not tested but reviewed. If you say it works, it is ready to merge from my side. 👍

Do not merge yet! I just found an error in the python bc...

2021-09-08 17:12 UTC, mcwimm commented
> > not tested but reviewed. If you say it works, it is ready to merge from my side. 👍
> 
> Do not merge yet! I just found an error in the python bc...

I fixed it... however, the python bc output is written after each iteration. That means if OGS doesn't converge the output of one time step is written mutltiple times. I haven't yet had an idea for a query that avoids this. Do you know if it is possible to get a feedback from OGS indicating if it is converged?

FYI: The procedure is as follows: for each time step, the BC runs through all the cells, calling them several times in succession (normally 5 times). When all cells have been called and OGS has not converged, the whole process starts over and over again.

2021-09-10 06:55 UTC, jbathmann commented
I think there is no such functionality in the python_bc of ogs yet. You might ask Christoph (christoph.lehmann@ufz.de), whether he has an advice... He knows such things...(?)

2021-09-10 07:02 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/NetworkOGSLargeScale3D/NetworkOGSLargeScale3D.py
> +        SimpleNetwork.calculateBGresourcesTree()
:+1:

2021-09-10 07:07 UTC, jbathmann commented
> > > not tested but reviewed. If you say it works, it is ready to merge from my side. +1
> > 
> > 
> > Do not merge yet! I just found an error in the python bc...
> 
> I fixed it... however, the python bc output is written after each iteration. That means if OGS doesn't converge the output of one time step is written mutltiple times. I haven't yet had an idea for a query that avoids this. Do you know if it is possible to get a feedback from OGS indicating if it is converged?
> 
> FYI: The procedure is as follows: for each time step, the BC runs through all the cells, calling them several times in succession (normally 5 times). When all cells have been called and OGS has not converged, the whole process starts over and over again.

You could try to check, whether the timestep has been reached before? 
`
if t_remember != t:
    do crazy stuff with output
    t_remember = t`

2021-09-10 12:21 UTC, merged