[TML] Introduce belowground competition concept 'symmetric ZOI'
jbathmann/pyMANGA pull request #145
Opened 2022-06-02 11:03 UTC by mcwimm

Below-ground competition concept based on BETTINA ODD 2017:
symmetric zone of influence (no salinity)

2022-06-02 16:00 UTC, jvollhueter requested changes
Looks nice! The only thing I noticed is a typo.

2022-06-02 16:00 UTC, jvollhueter commented on TreeModelLib/BelowgroundCompetition/__init__.py
> +from. SymmetricZOI import SymmetricZOI
```suggestion
from .SymmetricZOI import SymmetricZOI
```

2022-06-21 10:20 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/SymmetricZOI/SymmetricZOI.py
> +        self.makeGrid(args)
Can we move the makeGrid function to TreeModel?

2022-06-21 10:20 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/SymmetricZOI/SymmetricZOI.py
> +        self.t_end = t_end
Move self.xe/ye and times to TreeModel?

2022-06-21 10:22 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/SymmetricZOI/SymmetricZOI.py
> +        trees_present = root_radius[np.newaxis, np.newaxis, :] > distance
Maybe add a comment expalinin the array

2022-06-21 10:25 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/SymmetricZOI/SymmetricZOI.py
> +                      np.array(self.ye)[np.newaxis, np.newaxis, :])**2)**0.5)
This array may kill the ram. Can you avoid arrays this big?

2022-06-29 06:49 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/SymmetricZOI/SymmetricZOI.py
> +        self.makeGrid(args)
Good idea!

2022-06-29 06:50 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/SymmetricZOI/SymmetricZOI.py
> +        self.t_end = t_end
Yes, except for r_root as this variable might not exist in all concepts (e.g. Kiwi), right?

2022-06-29 06:53 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/SymmetricZOI/SymmetricZOI.py
> +                      np.array(self.ye)[np.newaxis, np.newaxis, :])**2)**0.5)
Yes. But let's put this in a new issue/PR as this kind of arrays occur in multiple moduls.

2022-07-01 08:33 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/SymmetricZOI/SymmetricZOI.py
> +        self.t_end = t_end
I agree

2022-07-01 15:03 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/__init__.py
> +from. SymmetricZOI import SymmetricZOI
solved

2022-07-01 15:04 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/SymmetricZOI/SymmetricZOI.py
> +        self.t_end = t_end
see issue #147

2022-07-04 10:57 UTC, jbathmann commented
Looks good.
If @jvollhueter agrees, I see it as ready to merge.

2022-07-05 15:01 UTC, jvollhueter commented
@jvollhueter agrees!

2022-07-05 15:06 UTC, merged