Module Benchmarks
jbathmann/pyMANGA pull request #163
Opened 2022-09-14 09:20 UTC by mcwimm

started with web page input

NO REVIEW NEEDED AT THE MOMENT

2022-09-16 14:50 UTC, jbathmann reviewed
Looks good! But we already discussed it quite a bit. So I am curious on @zaphod-bx and @jvollhueter opinion. :+1: 
Why do you repeat some of the figure contents? (a)

2022-09-16 14:50 UTC, jbathmann commented on web/content/en/docs/Benchmarks/_index.md
> +With SimpleKiwi, below- and above-ground modules that depend on tree geometries (i.e. crown and root radius) do not need to be tested.
Why not? ;)

2022-09-16 14:50 UTC, jbathmann commented on Benchmarks/ModuleBenchmarks/BelowgroundCompetition/SZoiFixedSalinity/SZoiFixedSalinity.xml
> +        <output_times> [2e6, 5e8] </output_times>
With #168 it should be possible to omit some of the output?

2022-09-16 14:55 UTC, mcwimm commented on web/content/en/docs/Benchmarks/_index.md
> +With SimpleKiwi, below- and above-ground modules that depend on tree geometries (i.e. crown and root radius) do not need to be tested.
because it doesn't make sense? I welcome any suggestion on a proper argument :)

2022-09-16 14:56 UTC, mcwimm commented on Benchmarks/ModuleBenchmarks/BelowgroundCompetition/SZoiFixedSalinity/SZoiFixedSalinity.xml
> +        <output_times> [2e6, 5e8] </output_times>
with the old implementation only 2 outputs were written. I'll update the xml files when #168 is merged.

2022-09-16 14:59 UTC, jbathmann commented on web/content/en/docs/Benchmarks/_index.md
> +With SimpleKiwi, below- and above-ground modules that depend on tree geometries (i.e. crown and root radius) do not need to be tested.
```suggestion
With SimpleKiwi, below- and above-ground modules that depend on tree geometries (i.e. crown and root radius) do not grow during the simulation as tree size is only defined in dependence on dbh.
Hence, we do not test the concepts, which depend on crown and root radius as the competition behavior does not change over time.
```

2022-09-22 05:39 UTC, jvollhueter reviewed
Ready to merge!

2022-09-22 11:11 UTC, jbathmann commented on Benchmarks/ModuleBenchmarks/BelowgroundCompetition/SZoiFixedSalinity/SZoiFixedSalinity.xml
> +        <output_times> [2e6, 5e8] </output_times>
#168 is merged

2022-09-22 12:42 UTC, jbathmann commented
> Ready to merge!

@mcwimm, can you please add a german version of the documentation?

2022-09-22 12:43 UTC, jbathmann requested changes
I think the English version is great. Could you please translate it and add the German pendant?

2022-10-04 12:47 UTC, mcwimm commented
> I think the English version is great. Could you please translate it and add the German pendant?

Ok. Added link to en. version :)

2022-10-04 12:55 UTC, mcwimm commented
@jbathmann @jvollhueter  In the current preview some tables are completely messed up although I didn't change them and the local preview (`hugo server`) looks good. Any ideas?

2022-10-05 15:46 UTC, jbathmann commented
I have no idea. @jvollhueter ?

2022-10-11 07:21 UTC, merged