DOC: exmouth gulf
jbathmann/pyMANGA pull request #65
Opened 2020-10-15 12:47 UTC by jvollhueter

First draft of the documentation for the model setup Exmouth gulf

2020-10-15 13:16 UTC, jbathmann requested changes
Ich finde den Anfang gut!
Was noch fehlt:

- Auslagern der Setupfile-Beschreibung
- Beschreibung der Ergebnisse
- Abbildungen von Ergebnissen

2020-10-15 13:16 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Installation_exmouth.md
> +Das Programm lässt sich jetzt durch das Öffnen eines Terminals in der Hauptebene von pyMANGA durch Eingabe des Befehls "python main.py -i /Model_Exmouth_Gulf/setup_pymanga.xml" starten. Falls der Sta
Eventuell: 

python Absolute/Path/To/main.py -i Absolute/Path/To/Model_Exmouth_Gulf

2020-10-15 13:16 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/doc_full_model.md
> +Im folgenden werden die wichtigsten Dateien des Setups genauer beschrieben. In der Hauptebene des Setups liegen ein Ordner "Input_OGS" und die zwei Dateien Avicennia.py und setup_pymanga.xml. Wie der
```suggestion
Im folgenden werden die wichtigsten Dateien des Setups genauer beschrieben. In der Hauptebene des Setups liegen ein Ordner "Input_OGS" und die zwei Dateien Avicennia.py und setup_pymanga.xml. Wie der Name vermuten lässt, befinden sich im Ordner "Input_OGS" die für die Grundwassermodellierung nötigen Modelleingangsdateien. Avicennia.py enthält Einstellungen zur Mangrovenart "Graue Mangrove". Hier können zum Beispiel die Wachstumsgeschwindigkeit, maximale Wachstumshöhe, maximale Lebenszeit und andere individuenspezifische Parameter definiert werden. Die Steuerdatei "dateiname.xml" stellt das Herzstück eines jeden Modellsetups dar. Sie wird aufgerufen, um einen Modelllauf zu starten. Das Dokument README.md dient lediglich zu Informationszwecken und spielt bei der Modellierung mit pyMANGA keine Rolle.
```

2020-10-15 13:16 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/doc_full_model.md
> +Die Steuerdatei eines jeden pyMANGA-Setups wird im xml-Format geschrieben. Hier werden alle Einstellungen zur Modellierung vorgenommen. Im Folgenden die Steuerdatei für das Setup Exmouth-Golf genauer
Der Inhalt der Datei wird ist unter ... genauer erläutert. Und den Folgenden, allgemeinen Content evtl in einen anderen Menüpunkt?

2020-10-15 13:16 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/doc_full_model.md
> +Die Steuerdatei eines jeden pyMANGA-Setups wird im xml-Format geschrieben. Hier werden alle Einstellungen zur Modellierung vorgenommen. Im Folgenden die Steuerdatei für das Setup Exmouth-Golf genauer
Also sowas wie "Detaillierte Beschreibung eines Beispiel-Inputs"

2020-10-15 13:16 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/doc_full_model.md
> +Derzeit gibt es noch eine weitere Klasse für "type", "SimpleTest". Diese soll für Beispiel-Setups und zur Überprüfung der korrekten Berechnung von Setups angewendet werden und eignet sich nicht zur M
Informationen über weitere mögliche Klassen können unter "LINK TO DOXYGEN PAGE" nachgeschlagen werden

2020-10-15 13:16 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/doc_full_model.md
> +Im dritten und letzten Hauptpunkt des Abschnitts "tree_dynamics" kann das dynamische Konzept des Baumwachstums und -sterbens ausgewählt werden. Hierfür stehen drei zur Verfügung, "SimpleKiwi", "Simpl
Hab ich wirklich simpleKiwi verwendet? oO

2020-10-15 13:16 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/doc_full_model.md
> +In diesem Setup ist eine Visualisierung der Modellierung während eines Modelllaufs ausgeschaltet. Für den Punkt "type" wird hierzu "NONE" gewählt. Mit "SimplePypolot" würde die Position und der Krone
Hier würde ich auf das beispielbild verzichten

2020-12-18 12:44 UTC, jvollhueter commented
In this commit I have translated the already existing content into english. Both, the english and the german version, still need some improvements, especially links, grammar, spelling and typos need to be improved before merging into the master.
What is still missing in content now:
- Description of the boundary conditions in the groundwater model
- Visualizations

At the moment I am still working on the visualizations, especially the representation of the salinity in the figure with the placement of the mangroves in the model area is still causing problems.

2021-02-19 15:14 UTC, closed without merging