DOC: exmouth gulf
jbathmann/pyMANGA pull request #74
Opened 2021-02-19 15:20 UTC by jvollhueter

...

2021-03-30 11:40 UTC, jbathmann requested changes

2021-03-30 11:40 UTC, jbathmann commented on test/SmallTests/Test_Setups_small/AllSimple_WithOutput.xml
> -
Why is this deleted here?

2021-03-30 11:40 UTC, jbathmann commented on test/SmallTests/Test_Setups_small/FIXEDSAL_BETTINA.xml
> -<?xml version="1.0" encoding="ISO-8859-1"?>
Why is this deleted here?

2021-03-30 11:40 UTC, jbathmann commented on test/SmallTests/Test_Setups_small/FON_SAZOI_KIWI.xml
> -<?xml version="1.0" encoding="ISO-8859-1"?>
Why is this deleted here?

2021-03-30 11:40 UTC, jbathmann commented on test/SmallTests/Test_Setups_small/SimpleHydro_SAZOI_BETTINA.xml
> -<?xml version="1.0" encoding="ISO-8859-1"?>
Why is this deleted here?

2021-03-30 11:40 UTC, jbathmann commented on test/SmallTests/test_small.py
> -import sys
Why is this deleted here?

2021-03-30 11:40 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Der_Exmouth_Golf.md
> +<p>
Hattest du hier nicht ne neuere Version erstellt?

2021-03-30 11:40 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Der_Exmouth_Golf.md
> +<figcaption><font size = "1"><i><b>Abbildung 2:</b> Luftbild Exmouth-Golf</i></font></figcaption>
hier (und bei den anderen dronenbildern) müssen wir noch irgendwas einfügen. z.b. \copyright Ruth Reef

2021-03-30 11:40 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Installation_exmouth.md
> +Das Modellsetup kann hier -Link folgt nach Absprache- heruntergeladen werden. Der Ordner kann an einer beliebigen Stelle entpackt werden, es bietet sich aber zum Beispiel die Hauptebene der pyMANGA-I
Setup ordner erstellen im root. Irgendwas mit \Benchmarks oder so und dann verlinken

2021-03-30 11:40 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Installation_exmouth.md
> +Das Programm lässt sich jetzt durch das Öffnen eines Terminals in der Hauptebene von pyMANGA durch Eingabe des Befehls
```suggestion
Das Setup lässt sich jetzt durch das Öffnen eines Terminals in der Hauptebene von pyMANGA durch Eingabe des Befehls 
```

2021-03-30 11:40 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/_index.md
> +Ein Modell zur Simulierung des Mangroven-Wachstums in einer vom Tidenhub beeinflussten Golfregion im westlichen Australien.
kannst du hier vielleicht noch nen catchie-bild einfügen?

2021-03-30 11:40 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/doc_full_model.md
> +## constant_contributions.npy
Ich glaube die Datei kann aus dem Setup gelöscht werden, oder?

2021-03-30 11:40 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/doc_full_model.md
> +## quad.vtu
Die Datei kann gelöscht werden

2021-03-30 11:40 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/doc_full_model.md
> +## testbulk.vtu
Beschreibung fehlt - bulk mesh

2021-03-30 11:40 UTC, jbathmann commented on web/content/de/docs/Erste_Schritte/_index.md
> +weight: 1
?

2021-03-30 11:40 UTC, jbathmann commented on web/content/de/docs/Steuerdatei/_index.md
> +---
Kannst du hier noch eine verlinkung zur doxygen-seite einbauen?

2021-03-30 11:40 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/Exmouth_Gulf.md
> +---
Schau ich später an - erstmal deutsch fertig machen

2021-03-30 11:40 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/Installation_exmouth.md
> +---
s.o.

2021-03-30 11:40 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/_index.md
> +---
s.o.

2021-03-30 11:40 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/doc_full_model.md
> +---
s.o.

2021-03-30 11:40 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +---
s.o.

2021-03-30 11:40 UTC, jbathmann commented on web/content/en/docs/Steuerdatei/_index.md
> +---
s.i.

2021-03-30 11:40 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +<figcaption><font size = "1"><i><b>Abbildung 1:</b> Modellgebiet</i></font></figcaption>
caption aus paper übernehmen, wenn veröffentlicht

2021-03-30 11:40 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +MARKER
ist glaub ich zu viel

2021-03-30 11:40 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +Im Modell <b>"Model Without Feedback"</b> werden die dynamischen Veränderungen der abiotischen Einflüsse (Gezeiten, Grundwasserneubildung und Salzgehalt des Meerwassers (!!!!!!nicht dynamisch abgedil
richtig

2021-03-30 11:40 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +
hier findest du im paper eine beschreibung

2021-03-30 11:40 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +
das braucht am ende alles nochmal nen update

2021-03-30 11:40 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +# Runtime [Arbeitstitel]
Ressourcenkonkurrenz?

2021-03-30 11:40 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +<p>
irgendwie nicht interaktiv. :(

2021-03-30 11:40 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +<figcaption><font size = "1"><i><b>Abbildung 4:</b> Ergebnisse</i></font></figcaption>
bissle ausführlichere caption. evtl einfach aus paper. (so wie bei den anderen entnommenen abbildungen)

2021-03-30 11:40 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +Im vorangegangenem Abschnitt wurde gezeigt, dass pyMANGA mit der Berücksichtigung von Salzkonzentration im Bodenwasser und des Tidenhubs in der Lage ist, die für Mangrovenwälder typischen Waldstruktu
Gute einleitung. Kannst du die Aussagen aus dem Paper übernehmen?

2021-04-19 08:41 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +Zur Evaluierung der Modellergebnisse werden sowohl Allometrydaten aus einer Transektenmessung, als auch Messergebnisse einer Langzeitstudie verwendet. In der Langzeitstudie werden die Auswirkungen vo
Für weitere Arbeiten: Netlify schein latex-format zu verwenden. Das bedeutet, dass ein einfacher Zeilenumbruch nicht als umbruch abgebildet wird. Daher kann jeder Satz eine eigene Zeile bekommen, was das ganze leichter für Versionskontrolle verwendbar macht.
Ein doppelter Zeilen Umbruch in der Source führt zu einem einfachen Umbruch im Target.

2021-04-19 08:43 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +Die Höhenprofile aus dem digitalen Oberflächenmodell der fünf Transekte (<a href="/de/docs/beispielmodell_exmouth_gulf/ergebnisse/#Abbildung_2"> Abbildung 2 A</a>) wurden übereinander gelegt und aus
```suggestion
Die Höhenprofile aus dem digitalen Oberflächenmodell der fünf Transekte (<a href="/de/docs/beispielmodell_exmouth_gulf/ergebnisse/#Abbildung_2"> Abbildung 2 A</a>) wurden übereinander gelegt und aus den fünf Signalen (<a href="/de/docs/beispielmodell_exmouth_gulf/ergebnisse/#Abbildung_2">Abbildung 2 B</a>) die Geländeoberkante aus der Grundlinie der Signals interpoliert (<a href="/de/docs/beispielmodell_exmouth_gulf/ergebnisse/#Abbildung_2">Abbildung 2 C</a>)
```

2021-04-19 08:43 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +## Modellvarianten
Da ist irgendwas mit dem Layout schiefgegangen

2021-04-19 08:44 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +
Schau dir mal das Preview an. Keine Ahnung,was da schiefgegangen ist

2021-04-19 08:49 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +Der Salzgehalt des Meerwassers wurde mit 50 g/kg festgelegt, das Bodenwasser am landseitigem Ende des Transsekts bekam eine Salinität von 70 g/kg zugewiesen. Durch die Transpiration der Mangroven erh
```suggestion
Der Salzgehalt des Meerwassers wurde mit 50 g/kg festgelegt, das Bodenwasser am landseitigem Ende des Transsekts bekam eine Salinität von 70 g/kg zugewiesen. Durch die Transpiration der Mangroven erhöhen diese lokal den Salzgehalt. Der Wasserstand wird in Form des hydrostatischen Drucks an der see- und landseitigen Kante des Modellgebiebts bestimmt. Zur Abbildung der Gezeiten wurde der seeseitige Wasserstand dabei als dynamische Randbedingung 1. Art in das Modell integriert. Als Datengrundlage dienten hier die Wasserstandsmessungen des Deparment of Transport der Government of Western Australia. Der landseitige Wasserstand wird über eine konstante Randbedingung 1. Art abgebildet. Die Evapotranspiration der Bäume wird durch Senken im Bereich der Wurzeln abgebildet (Vgl Abbildung 3). Zufluss in Form von Niederschlag wird indirekt über den Salzgehalt am landseitige Rand des Modellgebiets berücksichtigt. Zuflüsse in Form von Niederschlag wurden nicht als eigene Randbedingung abgebildet, sondern sollen mit über die Randbedingung 1. Art am landseitigen Modellende integriert werden. Die hier nicht erwähnten Modellseiten werden alle als No-Flow-Randbedingung definiert. Eine schematische Darstellung des Modellgebiets stellt auch <a href="/de/docs/beispielmodell_exmouth_gulf/ergebnisse/#Abbildung_1">Abbildung 1</a>
```

2021-04-19 08:51 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +In diesem Projekt wurden mit Hilfe des pyMANGA-Modells zwei Prozesse genauer Betrachtet. Zum einen sollte die Entwicklung der typischen Strukturen in Mangrovenwäldern abgebildet werden, zum anderen s
Vielleicht lieber "In dieser Arbeit..:" als "In diesem Projekt..."?

2021-04-19 08:51 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +<p>
Nice! Er geht wieder?!

2021-04-19 08:53 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +<p>
Vielleicht kannst du die %-Achse auf +-10% setzen? Dann sieht es nach weniger fluktuationen aus. :P

2021-04-19 08:56 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +Die Ergebnisse des "<b>Full Models</b>" stimmen mit den gemessenen Felddaten qualitativ überein (siehe <a href="/de/docs/beispielmodell_exmouth_gulf/ergebnisse/#Abbildung_4">Abbildung 4</a>). Dies tr
In der aktuellen Paper-Version habe ich die Übereinstimmung quantifiziert. Die R2-Werte findest du im entsprechenden Kapitel der Ergebnisse.

2021-04-19 08:57 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +Aufgrund der größeren Auswirkungen des Tidenhubs im seenahen Bereich kann das Modell "<b>Without Tide</b>" sowohl die Bäumhöhen als auch den Porenwassersalzgehalt hier nur mit reltiv großer Abweichun
```suggestion
Aufgrund der größeren Auswirkungen des Tidenhubs im seenahen Bereich kann das Modell "<b>Without Tide</b>" sowohl die Bäumhöhen als auch den Porenwassersalzgehalt hier nur mit relativ großer Abweichung im Vergleich zum "<b>Full Model</b>" abbilden. Je weiter man sich aber in Richtung Festland bewergt, desto geringer werden die Wasserstandsschwankungen aufgrund der Gezeiten. Die Baumhöhen und Salzgehalte können in diesem Bereich (x > 75 m) mit geringeren relativen Abweichungen zum Full Model abgebildet werden.
```

2021-04-19 08:59 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +Im vorangegangenem Abschnitt wurde gezeigt, dass pyMANGA mit der Berücksichtigung von Salzkonzentration im Bodenwasser und des Tidenhubs in der Lage ist, die für Mangrovenwälder typischen Waldstruktu
```suggestion
Im vorangegangenem Abschnitt wurde gezeigt, dass pyMANGA mit der Berücksichtigung von Salzkonzentration im Bodenwasser und des Tidenhubs in der Lage ist, die für Mangrovenwälder typischen Waldstrukturen abzubilden. Mit Hilfe der umfangreichen Parametrisierungsmöglichkeiten des Baumwachstumsmodells (siehe hierzu auch den Abschnitt <a href="/de/docs/beispielmodell_exmouth_gulf/ergebnisse/#Parametrisierung">Parametrisierung</a>) kann mit pyMANGA auch das Wachstum einzelner bestimmter Individuenarten untersucht werden. Verschiedene Mangrovenarten zum Beispiel weisen verschiedene Toleranzen gegenüber zu hohen Salzgehalten auf. In diesem Projekt wurde das Wachstumsverhalten der beiden Arten Avicennia marina (<a href="https://www.biologie-seite.de/Biologie/Avicennia_marina">"graue Mangrove"</a>) und Rhizophora mangle (<a href="https://www.biologie-seite.de/Biologie/Rote_Mangrove">"rote Mangrove"</a>) genauer betrachtet.
```

2021-04-19 09:00 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +<img src="/pictures/exmouth_gulf/formel_normierung_speziendominanz.jpg" style="width:45%">
Dann hier entweder ohne summe, oder genau wie die nachfolgende formel...

2021-04-19 09:15 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +In der Literatur gibt es Hinweise darauf, dass sich Mangroven über die Zeit an ihre Umweltbedingungen anpassen. Eine niedrigere Salzkonzentration im Bodenwasser sorgt für eine höhere Xylemleitfähigke
physiological plasticity = Die Möglichkeit die physiologie des baumes an umweltbedingungen anzupassen.

2021-04-19 19:00 UTC, jvollhueter commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +Zur Evaluierung der Modellergebnisse werden sowohl Allometrydaten aus einer Transektenmessung, als auch Messergebnisse einer Langzeitstudie verwendet. In der Langzeitstudie werden die Auswirkungen vo
Das würde ich bei den Aufräumarbeiten dann vielleicht für die gesamte Homepage ändern - das wäre glaube ich wirklich sehr hilfreich

2021-04-20 11:33 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +<td style="text-align: left;">Maintenance cost per biomass MARKER: Übersetzung</td>
Resourcenbedarf zur Biomasseerhaltung

2021-04-27 07:11 UTC, jbathmann commented on Benchmarks/Exmouth_Gulf/full_model/TODOS
> +--Seed setzen
can you either translate or delete this file?

2021-04-27 07:11 UTC, jbathmann commented on Benchmarks/Exmouth_Gulf/full_model/vtu_collection.pvd
> +</VTKFile>
we don't need this file

2021-04-27 07:14 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/Exmouth_Gulf.md
> +The Exmouth Gulf is located on the west coast of Australia in the state Western Australia (see also <a href="/docs/sample_model_exmouth_gulf/exmouth_gulf/#Figure_1">Figure 1</a>). The bay is a semi-a
```suggestion
The Exmouth Gulf is at the west coast of Australia in the state Western Australia (see also <a href="/docs/sample_model_exmouth_gulf/exmouth_gulf/#Figure_1">Figure 1</a>). The bay is a semi-arid estuarine system with extensive coastal wetlands. The area is very important because of its great biodiversity, including migrating whales and seabirds. It is considered as one of the largest mostly anthropologically unchanged estuarine systems in the world. Therefore, tourism, recreation and commercial fishing play an important role in the area. Numerous mangroves grow on the approx. 2600 km² large headland, which consists of numerous inlets and is crossed by tidal creeks. With an average tidal range of about 1.8 meters, the mangroves are exposed to tidal flooding with salt water.
```

2021-04-27 07:15 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/Exmouth_Gulf.md
> +<figcaption><font size = "1"><i><b>Figure 1:</b> Location of study area in Exmouth Gulf in Western Australia (&copy; <a href="https://www.google.de/maps">Google Maps</a>)</i></font></figcaption>
```suggestion
<figcaption><font size = "1"><i><b>Figure 1:</b> Location of study site in the Exmouth Gulf in Western Australia (&copy; <a href="https://www.google.de/maps">Google Maps</a>)</i></font></figcaption>
```

2021-04-27 07:15 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/Exmouth_Gulf.md
> +The <a href="/docs/sample_model_exmouth_gulf/exmouth_gulf/#Figure_2">Figure 2</a> und <a href="/docs/sample_model_exmouth_gulf/exmouth_gulf/#Figure_3">3</a> show the same section of the Exmouth Gulf
```suggestion
<a href="/docs/sample_model_exmouth_gulf/exmouth_gulf/#Figure_2">Figure 2</a> and <a href="/docs/sample_model_exmouth_gulf/exmouth_gulf/#Figure_3">3</a> show the same section of the Exmouth Gulf from different perspectives. The system of rivers and smaller streams in the mangrove forests can be seen as well.
```

2021-04-27 07:18 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/Exmouth_Gulf.md
> +<a href="/docs/sample_model_exmouth_gulf/exmouth_gulf/#Figure_4">Figure 4</a> shows the root system formed by the gray mangroves. Due to the anoxic conditions in the subsoil of the mangrove forests,
```suggestion
<a href="/docs/sample_model_exmouth_gulf/exmouth_gulf/#Figure_4">Figure 4</a> shows the root system formed by the gray mangroves. As an adaption to the anoxic conditions in the subsoil of the mangrove forests, the gray mangrove have pneumatophores. Those are aerial roots, which partly lie above the water surface Thereby, they allow plant respiration even at high tide..
```

2021-04-27 07:19 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/Installation_exmouth.md
> +In order to start a model run with the setup on your own computer, file paths references to input files have to be adjusted in the XML control file. All file paths in the control file are specified a
```suggestion
In order to start a model run with the setup on your own computer, file path references to input files have to be adjusted in the XML control file. All file paths in the control file are absolute, so each path starts with "/home/..." under Ubuntu and with the letter of the drive under Windows. If the location of the setup is not changed, the control file is located under the following path:
```

2021-04-27 07:21 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/Installation_exmouth.md
> +Groundwater modeling with OGS is performed using an additional Python script. Among other things, this script provides values for the tidal range from the file &bdquo;EXM_Jan-Jul_2019.txt&ldquo; for
```suggestion
Groundwater modeling with OGS is performed using an additional Python script. Among other things, this script provides values for the tidal range from the file &bdquo;EXM_Jan-Jul_2019.txt&ldquo; for OGS, puts these data into a loop (since the modeling period is significantly longer than the period of the tidal data) and provides an adjustment of the mean water level. The file location of the &bdquo;EXM_Jan-Jul_2019.txt&ldquo;-file must be adapted to the local folder structure, in the script (&bdquo;python_script.py&ldquo;) at line 140 f..
```

2021-04-27 07:23 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +As already described in the <a href="/docs/sample_model_exmouth_gulf/exmouth_gulf/">introductory chapter</a>, there are numerous mangrove forests in the Exmouth Gulf. With the help of MANGA, the grow
I usually use porewater instead of "pore water"

2021-04-27 07:23 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +A transect 185 m long and 10 m wide is represented in the model (<a href="/docs/sample_model_exmouth_gulf/model_results/#Figure_1">Figure 1</a>).
```suggestion
A 185 m long and 10 m wide transect is represented in the model (<a href="/docs/sample_model_exmouth_gulf/model_results/#Figure_1">Figure 1</a>).
```

2021-04-27 07:24 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +Allometry data from a transect measurement, as well as measurement results from a long-term study, are used to evaluate the model results. The long-term study documents the effects of fertilization o
```suggestion
Allometry data from a transect measurements, as well as measurement results from a long-term study, are used to evaluate the model results. The long-term study documents the effects of fertilization on the growth of 72 mangroves, half of them are located on the landward and half of them on the seaward side of the transect (see also <a href="/docs/sample_model_exmouth_gulf/model_results/#Figure_4">Figure 4</a>).
```

2021-04-27 07:27 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +In the model "<b>Model Without Feedback</b>" the dynamic changes in abiotic influences (tides, groundwater recharge and salinity of seawater) are included via boundary conditions. The influence of pl
```suggestion
In the model "<b>Model Without Feedback</b>" the dynamic changes in abiotic influences (tides, groundwater recharge and salinity of seawater) are included via boundary conditions. The influence of plant water extraction on pore water salinity was not accounted for.
```

2021-04-27 07:29 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +Since each mangrove is represented as a single individual, a spatial discretization in proper sense does not exist. Temporally, the tree growth model is discretized with a time step length of half a
```suggestion
Since each mangrove is represented as a single individual, there is no real spatial discretization. Temporally, the tree growth model is discretized with a time step length of half a year (1&nbsp;a&nbsp;=&nbsp;365.25&nbsp;d).
```

2021-04-27 07:31 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +The salinity of the seawater was set at 50 g/kg, the pore water at the landward end of the transect was assigned a salinity of 70 g/kg. The transpiration of the mangroves locally increases the salini
```suggestion
The salinity of the seawater was set at 50 g/kg, the pore water at the landward end of the transect was assigned a salinity of 70 g/kg. The transpiration of the mangroves locally increases the salinity. The water level is determined in terms of hydrostatic pressure at the seaward and landward ends of the model area. In order to represent the tides, the lake-side water level was integrated into the model as a dynamic Dirichlet boundary condition. The water level measurements of the Department of Transport of the Government of Western Australia served as data basis. The land-based water level is represented by a constant Dirichlet boundary condition. Evaporation of the trees is integrated by sink terms in the area of the roots (see also <a href="/docs/sample_model_exmouth_gulf/model_results/#Figure_3">Figure 3</a>). Inflow in the form of precipitation is indirectly considered via salinity at the landward edge of the model area. The model boundaries which are not mentioned explicitly, are all defined as no flow boundary conditions. <a href="/docs/sample_model_exmouth_gulf/model_results/#Figure_1">Figure 1</a> shows a schematic diagram of this.
```

2021-04-27 07:33 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +For representing the mangroves in the model area, it is necessary to establish a stable population, which means to reach quasi-stationary conditions. For this purpose, 30 mangroves are randomly posit
```suggestion
For representing the mangroves in the model area, it is necessary to establish a stable population, which means to reach quasi-stationary conditions. For this purpose, 30 mangroves are randomly positioned in the model area as seedlings. In each time step (length: half a year), 30 new mangroves are added, which are also randomly positioned in the model area. Due to the competition-based tree growth model, these new mangroves die more or less quickly. Thus, the probability that a young mangrove in the catchment area of an already older one dies again very quickly is very high. The reason for this is the above-ground competition, especially the lack of sunlight. Due to the concentration of salinity, caused by extraction of fresh water from the other mangroves, salt plumes are formed in the pore water. These lead to growth penalties for the mangroves located downstream (especially for young mangroves). Different mangrove species have varying tolerance to high salt concentrations. In this research, the two species Avicennia marina ("gray mangrove") and Rhizophora mangle ("red mangrove") were studied in more detail.
```

2021-04-27 07:35 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +In this research, two processes were viewed more closely with the help of the MANGA model. On the one hand, the development of typical structures in mangrove forests should be mapped, on the other ha
```suggestion
In this research, two processes were viewed more closely with the help of the MANGA model. On the one hand, the development of typical structures in mangrove forests is mapped, on the other hand, the growth behavior of the two mangrove species under different environmental conditions is investigated. In the following the results of the research are briefly summarized.
```

2021-04-27 07:37 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +In the following video the model area was divided into ten sectors. The dynamic development of the mangrove population and the salt concentration in the bottom water as well as the biomass of the man
```suggestion
In the following video the model area was divided into ten sectors. The dynamic development of the mangrove population and the salt concentration in the bottom water as well as the biomass of the mangroves in the individual sectors are shown. Compared to the previous visualization, one main cause of the formation of the typical forest structure can be seen in this video, namely the concentration of salinity in the pore water in certain areas. The high correlation between salt concentration and biomass in the individual sectors can be seen already from a model runtime of 40 years. Already from 100 years, the structure of typical mangrove forests is recognizable.
```

2021-04-27 07:38 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +The "Treatment Averages" plotted in <a href="/docs/sample_model_exmouth_gulf/model_results/#Figure_4">Figure 4</a> are two areas where mangroves growing have been long term studied in more detail. A
```suggestion
The "Treatment Averages" plotted in <a href="/docs/sample_model_exmouth_gulf/model_results/#Figure_4">Figure 4</a> are from mangroves that have been studied in more detail in long-term experiments. A comparison of the results of these observations with the modeling results also shows a high degree of agreement.
```

2021-04-27 07:39 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +In order to investigate the effects of taking into account the temporal dynamics of tides and plant water extraction on the salinity in the pore water, this effect was normalized using the following
```suggestion
In order to investigate the effects of the temporal dynamics of tides and plant water extraction on the salinity in the pore water, this effect was normalized using the following formula:
```

2021-04-27 07:40 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +Due to the greater effects of the tidal range in the area close to the see, the model "<b>Without Tide</b>" can only represent the tree heights and the pore water salinity here with a relatively larg
```suggestion
Due to the greater effects of the tidal range in the area close to the sea, the model "<b>Without Tide</b>" can only represent the tree heights and the pore water salinity here with a relatively large deviation compared to the "<b>Full Model</b>". However, with further inlands, the water level fluctuations due to tides become smaller. Tree heights and salinities can be represented in this range (x > 75 m) with smaller relative deviations from the "<b>Full Model</b>".
```

2021-04-27 07:41 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +The Model "<b>Without Feedback</b>" has problems mapping mangrove growth height as the "<b>Full Model</b>" does, especially in the middle to landward area (60 m < x < 165 m) of the transect. In this
```suggestion
The Model "<b>Without Feedback</b>" fails to predict mangrove growth height, especially in the middle to landward area (60 m < x < 165 m) of the transect. In this area the salinity of the pore water is concentrated by the plant water extraction, but this is not represented in this type of model.
```

2021-04-27 07:44 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +When looking at the mixed forests, it is noticeable that real mixed populations are existing only in a few individual sections. In most areas a clear dominance of one species is formed. These sharp t
```suggestion
When looking at the mixed forests, real mixed populations are existing only in a few individual sections. In most areas a clear dominance of one species is expressed. These sharp transitions between the individual dominance zones show that coexistence between the different species is only possible in areas of certain pore water salinities. The location of the boundaries and the change in species dominance d (slope of the curve) depend on the individual-specific parameters in the tree growth model. Soil water salinity is also affected by the number of individuals per area and tree heights. These two parameters are in turn influenced by the same individual-specific parameters. 
```

2021-04-27 07:47 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +Using the sensitivity analysis of the model with respect to species dominance, it was shown that species composition can be described by considering soil water balance and plant water withdrawal acro
```suggestion
Using the sensitivity analysis of the model with respect to species dominance, it was shown that species composition can be described by considering soil water balance and plant water withdrawal across the system boundary. By variation of just two parameters (see <a href="/docs/sample_model_exmouth_gulf/model_results/#Table_3">Table 3</a>) that directly affect tree water uptake, typical zonation patterns in mixed mangrove forests could be reproduced. This was accomplished even with roughly estimated plant-specific parameters for one of the two species. If the boundary conditions of the salt concentrations on the land- and seaward side are both chosen very high or very low, monoculture forests are formed. If a moderate mean value of the salinities is chosen, mixed forests of both species are formed. These show zones with clear dominance of one species, separated by sharp transitions. These transitions are shown to depend on the porewater salinity. The species composition in the model agrees with the measured field data.
```

2021-04-27 19:31 UTC, jvollhueter commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +<figcaption><font size = "1"><i><b>Abbildung 4:</b> Ergebnisse</i></font></figcaption>
done

2021-04-27 19:32 UTC, jvollhueter commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Ergebnisse.md
> +<td style="text-align: left;">Maintenance cost per biomass MARKER: Übersetzung</td>
Done

2021-04-27 19:33 UTC, jvollhueter commented on Benchmarks/Exmouth_Gulf/full_model/TODOS
> +--Seed setzen
is deleted - a detailed description is on the homepage

2021-04-27 19:33 UTC, jvollhueter commented on Benchmarks/Exmouth_Gulf/full_model/vtu_collection.pvd
> +</VTKFile>
deleted

2021-04-27 19:35 UTC, jvollhueter commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/Exmouth_Gulf.md
> +The Exmouth Gulf is located on the west coast of Australia in the state Western Australia (see also <a href="/docs/sample_model_exmouth_gulf/exmouth_gulf/#Figure_1">Figure 1</a>). The bay is a semi-a
Done

2021-04-27 19:37 UTC, jvollhueter commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/Exmouth_Gulf.md
> +<figcaption><font size = "1"><i><b>Figure 1:</b> Location of study area in Exmouth Gulf in Western Australia (&copy; <a href="https://www.google.de/maps">Google Maps</a>)</i></font></figcaption>
Done

2021-04-27 19:37 UTC, jvollhueter commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/Exmouth_Gulf.md
> +The <a href="/docs/sample_model_exmouth_gulf/exmouth_gulf/#Figure_2">Figure 2</a> und <a href="/docs/sample_model_exmouth_gulf/exmouth_gulf/#Figure_3">3</a> show the same section of the Exmouth Gulf
Done

2021-04-27 19:51 UTC, jvollhueter commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/Exmouth_Gulf.md
> +<a href="/docs/sample_model_exmouth_gulf/exmouth_gulf/#Figure_4">Figure 4</a> shows the root system formed by the gray mangroves. Due to the anoxic conditions in the subsoil of the mangrove forests,
Done

2021-04-27 19:52 UTC, jvollhueter commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/Installation_exmouth.md
> +In order to start a model run with the setup on your own computer, file paths references to input files have to be adjusted in the XML control file. All file paths in the control file are specified a
Done

2021-04-27 19:53 UTC, jvollhueter commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/Installation_exmouth.md
> +Groundwater modeling with OGS is performed using an additional Python script. Among other things, this script provides values for the tidal range from the file &bdquo;EXM_Jan-Jul_2019.txt&ldquo; for
done

2021-04-27 19:54 UTC, jvollhueter commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +As already described in the <a href="/docs/sample_model_exmouth_gulf/exmouth_gulf/">introductory chapter</a>, there are numerous mangrove forests in the Exmouth Gulf. With the help of MANGA, the grow
All replaced

2021-04-27 19:55 UTC, jvollhueter commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +A transect 185 m long and 10 m wide is represented in the model (<a href="/docs/sample_model_exmouth_gulf/model_results/#Figure_1">Figure 1</a>).
Done

2021-04-27 19:56 UTC, jvollhueter commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +Allometry data from a transect measurement, as well as measurement results from a long-term study, are used to evaluate the model results. The long-term study documents the effects of fertilization o
Done

2021-04-27 19:57 UTC, jvollhueter commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +Since each mangrove is represented as a single individual, a spatial discretization in proper sense does not exist. Temporally, the tree growth model is discretized with a time step length of half a
Done

2021-04-27 19:59 UTC, jvollhueter commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +The salinity of the seawater was set at 50 g/kg, the pore water at the landward end of the transect was assigned a salinity of 70 g/kg. The transpiration of the mangroves locally increases the salini
Done

2021-04-27 20:02 UTC, jvollhueter commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +For representing the mangroves in the model area, it is necessary to establish a stable population, which means to reach quasi-stationary conditions. For this purpose, 30 mangroves are randomly posit
Done

2021-04-27 20:02 UTC, jvollhueter commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +In this research, two processes were viewed more closely with the help of the MANGA model. On the one hand, the development of typical structures in mangrove forests should be mapped, on the other ha
Done

2021-04-27 20:04 UTC, jvollhueter commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +In order to investigate the effects of taking into account the temporal dynamics of tides and plant water extraction on the salinity in the pore water, this effect was normalized using the following
Done

2021-04-27 20:05 UTC, jvollhueter commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +Due to the greater effects of the tidal range in the area close to the see, the model "<b>Without Tide</b>" can only represent the tree heights and the pore water salinity here with a relatively larg
Done

2021-04-27 20:06 UTC, jvollhueter commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +The Model "<b>Without Feedback</b>" has problems mapping mangrove growth height as the "<b>Full Model</b>" does, especially in the middle to landward area (60 m < x < 165 m) of the transect. In this
Done

2021-04-27 20:08 UTC, jvollhueter commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +When looking at the mixed forests, it is noticeable that real mixed populations are existing only in a few individual sections. In most areas a clear dominance of one species is formed. These sharp t
Done

2021-04-27 20:09 UTC, jvollhueter commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +Using the sensitivity analysis of the model with respect to species dominance, it was shown that species composition can be described by considering soil water balance and plant water withdrawal acro
Done

2021-04-27 20:10 UTC, jvollhueter commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +In the model "<b>Model Without Feedback</b>" the dynamic changes in abiotic influences (tides, groundwater recharge and salinity of seawater) are included via boundary conditions. The influence of pl
Done

2021-04-27 20:11 UTC, jvollhueter commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/model_results.md
> +In the following video the model area was divided into ten sectors. The dynamic development of the mangrove population and the salt concentration in the bottom water as well as the biomass of the man
Done

2021-04-27 20:19 UTC, jvollhueter commented
With these last two commits the PR should be ready to merge. I have revised all the annotations and everything looks good in the local preview. In a new PR I would then revise the general structure in ./web - e.g. sort the images into folders, assign a line to each sentence, etc.

2021-04-27 20:22 UTC, jvollhueter commented
As I just saw, the formatting in the preview doesn't look good again in some places - maybe check with me briefly before merging so that I can change the formatting right away if necessary.

2021-04-28 08:50 UTC, jbathmann commented on web/content/en/docs/Sample_Model:_Exmouth_Gulf/Installation_exmouth.md
> +weight: 4
Please update

```suggestion
title: "Do it yourself"
linkTitle: "Do it yourself"
weight: 4
```

2021-04-28 08:51 UTC, jbathmann commented on web/content/de/docs/Beispielmodell:_Exmouth_Gulf/Installation_exmouth.md
> +linkTitle: "Setup selbst berechnen ARBEITSTITEL"
```suggestion
---
title: "Setup selbst berechnen"
linkTitle: "Setup selbst berechnen"
```

2021-04-28 08:51 UTC, jbathmann commented
I Think it looks good. two small changes are left and we are ready to merge! :-)

2021-04-28 09:36 UTC, merged